### ISSUE TITLE
How to run a kubectl command using rest API

### ISSUE THREAD

**Issue by vinaykumar612** [kubernetes-client/javascript#1095]
Lets say I have a command `kubectl get quota --watch`  which will give some response related to Quota.
I would like to get the same result using nodeJS source code. Can you please help here.

**Comment by mstruebing** [comment]
Wouldn't something like this provided in the examples would work?
https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/watch/watch-example.ts

**Comment by brendandburns** [comment]
In general, `kubectl` is a fairly complex piece of code for many operations.

You can find the source for it here:
https://github.com/kubernetes/kubectl/tree/master/pkg/cmd

You can then usually translate the Go code into the corresponding Javascript.

I'm going to close this issue, since it is more of a request for help than anything wrong with this library, and the relevant information has been provided.

If you get this code working, we'd be happy to take a PR to add it as an example.
