### ISSUE TITLE
No way to ignore duplicate cluster when loading config

### ISSUE THREAD

**Issue by datho7561** [kubernetes-client/javascript#1306]
**Describe the bug**
When loading the kubernetes configuration, there is no way to ignore duplicate cluster entries. I think this is a bug or a missing feature, since `kubectl` seems to work fine when there are duplicate cluster entries.

** Client Version **
`0.19.0`

** Server Version **
`1.26.6`

**To Reproduce**
Have multiple config files configured using `KUBECONFIG`. Have an identical cluster in both config files.

Then, invoke `new KubeConfig().loadFromDefault()`.

**Expected behavior**
`new KubeConfig().loadFromDefault()` should filter duplicate entries, or provide an option in the parameters to filter out duplicate entries.

** Example Code**
`new KubeConfig().loadFromDefault()`

**Environment (please complete the following information):**
 - OS: Linux
 - NodeJS Version: 18
 - Cloud runtime: ??? I have an OpenShift cluster

**Additional context**
none

**Comment by brendandburns** [comment]
This client doesn't support multiple config files in general (see the code here: https://github.com/kubernetes-client/javascript/blob/master/src/config.ts#L129)

The logic for loading from multiple files is complicated and not specified anywhere except for in the Golang client. It probably should never have been a feature of `kubectl` but it's too late for that now.

If you write a PR with comprehensive unit tests that mimics the behavior of the golang code, we can consider accepting it into this client library, but it is unlikely to be implemented otherwise.
