### ISSUE TITLE
Unhandled JSON parse errors in 'watch' cause the process to crash.

### ISSUE THREAD

**Issue by smcgunigal** [kubernetes-client/javascript#146]
The `watch` function does not ensure the data received is valid JSON before parsing it and does not handle any errors that may come from parsing. This can cause the process to restart when the api-server responds with non-valid JSON, which happens intermittently if the watch is used continuously. In particular, if the etcd cluster is unresponsive due to a timeout, the response is not able to be parsed and will cause a crash.

**Comment by scaccogatto** [comment]
If I watch `/apis/apps/v1/namespaces/{namespace}/deployments/{name}` the watcher just crashes because the reply contains no `type`.

I think it is related to: https://github.com/kubernetes-client/javascript/blob/01b721af83658b755ffa7bc3931383dc39e3a9fe/src/watch.ts#L63

Also I think that if k8s reply has no `type` we should just callback with type `undefined`.

**Comment by brendandburns** [comment]
Fixed by #148
