### ISSUE TITLE
Delete statefulset - replicate kubectl delete pod blahblah --force --grace-period=0

### ISSUE THREAD

**Issue by Daxcor69** [kubernetes-client/javascript#1506]
The odd time I have a statefulset pod that gets stuck in "Terminating"  I am using the following command in node:

```
try {
    k8sApi = kc.makeApiClient(k8s.AppsV1Api);
    await k8sApi.deleteNamespacedStatefulSet("bob", "fvtt", undefined, undefined, 0);
  } catch (e) {}
```
To remove the bad pod I use:

kubectl delete pods bob-0 --grace-period=0 --force

Is there a way in this sdk, to replicate the --force behaviour?

Thanks
Brad

**Comment by brendandburns** [comment]
I'm not sure what the `--force` flag sends to the server, your best bet is to use `kubectl --v=10 delete pods ...` which will display verbose logging including all URLs and bodies sent to the server. Then you'll be able to see what needs to be specified in this client (and then you can see if this client supports it)

I think `--force` might actually just mean send a `DELETE` instead of updating the status of the pod to `deleting` using a `PUT` but I'm not certain.
