### ISSUE TITLE
Reattempt of informer start() triggers all previous events

### ISSUE THREAD

**Issue by jobcespedes** [kubernetes-client/javascript#1598]
**Describe the bug**
Redo informer start() triggers all previous events. This is being done inside setTimeout periodically as a workaround since informer silently stop receiving events (see: https://github.com/kubernetes-client/javascript/issues/596)

** Client Version **
`1.0.0-rc4`

** Server Version **
e.g. `1.26.5`

**To Reproduce**
1. MakeInformer
2. Start informer
3. Set timeout starting informer in 30s
4. Trigger an update event in k8s for the informer to catch it
6. Wait for timeout to start informer again
7. See the update event in step 4 being reproduce again

**Expected behavior**

** Example Code**
```
const timeoutDelay = 1000 * 30;
const timeout = setTimeout(() => {
  if (informer) {
    informer
      .start()
      .then(() => {
        console.log("Informer refresh connection");
      })
      .catch((err) => {
        console.log("Informer refresh error");
        console.error(err);
      });
  }
}, timeoutDelay);
```

**Environment (please complete the following information):**
 - OS: linux
 - NodeJS Version: v18.14.2
 - Cloud runtime: EKS

**Additional context**
This is probably a secudary issue, being the primary that informer silently stop reproducing events, like in https://github.com/kubernetes-client/javascript/issues/596

**Comment by mstruebing** [comment]
I'm not an expert on how informers work but I guess this is because we have this data cached already and you do not instantiate a new one? As far as I know informers cache their data so it would make sense that they are replaying the events in case of a restart from my point of view.

As a workaround you could also try to save the last event you processed and skip until the event occurs and only process the newer ones?

Or can you try something like this and instantiate a new informer?:

```js
const timeoutDelay = 1000 * 30;
let informer;
const timeout = setTimeout(() => {
  informer = ... // instantiate a new informer
    informer
      .start()
      .then(() => {
        console.log("Informer refresh connection");
      })
      .catch((err) => {
        console.log("Informer refresh error");
        console.error(err);
      });
}, timeoutDelay);
```

**Comment by jobcespedes** [comment]
Hi @mstruebing,

Thank you for the suggestion. I thought about the option of starting a new informer. In this regard, I was wondering about the implications of not doing it correctly, reliably, and transparently, since the application using the informer cannot lose events. Another possible implication that I also wanted to avoid is memory leaks.

Regarding the mention of the cache, I also suspected that something has to do with the cache. I am reviewing the code in cache.ts to better understand what happens when using start(). I found the [Bookmark option](https://stackoverflow.com/questions/66080942/what-k8s-bookmark-solves). According to the description, the functionality of the option could be used to avoid the current behavior. However, I believe it is not yet programmed in the informer.

The fact that the informer/watcher stops silently is also something that I would like to understand and avoid.

**Comment by mstruebing** [comment]
If you find the root cause why this is happening we are more than happy to accept PRs.

If the informer replays all your events you could save the last processed event, at least I believe the event + resourceVersion should be unique so you are sure you start processing at the right event in case of a restart.
