### ISSUE TITLE
Make it run on frontend as well

### ISSUE THREAD

**Issue by novellat** [kubernetes-client/javascript#1752]
**Describe the bug**
We can connect to the cluster by setting the endpoint and auth token. So theoretically, why shouldn't we be able to use it from frontend? 
** Client Version **
e.g. `0.12.0`

** Server Version **
e.g. `1.19.1`

**To Reproduce**

**Expected behavior**

** Example Code**
Code snippet for what you are doing

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Linux]
 - NodeJS Version [eg. 10]
 - Cloud runtime [e.g. Azure Functions, Lambda]

**Additional context**

**Comment by brendandburns** [comment]
While this is potentially feasible, most Kubernetes clusters use a custom certificate authority root certificate. By design, most web browsers don't support loading custom root certificates for HTTP calls from within the browser for non-kubernetes security reasons.

Consequently, even if this client was ported to a browser HTTP/fetch library, the calls themselves would fail because `https` wouldn't work from the browser.

If someone wanted to add support for browser fetch in `release-1.x` we'd probably merge that PR, but it is of limited usefullness.

**Comment by novellat** [comment]
Thanks @brendandburns, that was a good observation, never realized you cannot bypass that in fetch!
