### ISSUE TITLE
Build and Deploy Docs is broken

### ISSUE THREAD

**Issue by clayrosenthal** [kubernetes-client/javascript#2023]
**Describe the bug**
The [build and deploy docs action](https://github.com/kubernetes-client/javascript/actions/workflows/deploy-docs.yml) appears to have been broken for about a year.

** Client Version **
0.22.2

** Server Version **
N/A

**To Reproduce**
1. Run the github action
2. Action fails

**Expected behavior**
Docs to be generated and published.

** Example Code**
[Your workflow](https://github.com/kubernetes-client/javascript/blob/master/.github/workflows/deploy-docs.yml)

**Environment (please complete the following information):**
 - OS: ubuntu 
 - NodeJS Version 20
 - Cloud runtime Github Action runner

**Additional context**
I want to read the docs and was bummed they aren't updated anymore.

Appears in the [action repo](https://github.com/JamesIves/github-pages-deploy-action/issues/1285) there is a fix by adding write permissions:
```
permissions:
  contents: write
```

**Comment by brendandburns** [comment]
fwiw, these docs aren't that good, since they are generated from the generated APIs. You're better off reading https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/

Closing, since the PR merged.

**Comment by passcod** [comment]
I am not in fact "better off" when I'm trying to find API information specific to these Typescript bindings and not the k8s API in general, and the linked PR merged with comments specifically saying "it is still not working" due to the CLA thing blocking the build.

At this point the docs are two years out of date. If you're not going to fix them, maybe remove the link from the readme?
