### ISSUE TITLE
GKE: Not compatible with gke

### ISSUE THREAD

**Issue by thesayyn** [kubernetes-client/javascript#241]
I couldn't get this work with GKE clusters.

I'm getting `masterAuth` data from @google-cloud/container and passing them to **applyToRequest** function which supposed to configure the `request` package for me.

`clientCertificate` paired with **request's** `cert` option.
`clientKey` paired with **request's** `key` option.
`clusterCaCertificate` paired with **request's** `ca` option.

Result is nasty `Error: unable to verify the first certificate`  :(

Is there anybody made this package work with GKE clusters ?

**Comment by brendandburns** [comment]
This definitely works with GKE clusters if you download everything into a `kubeconfig` file.

If you're trying to dynamically construct in memory then you may need to figure out the encoding/decoding of how those certificates are represented in the API.

So the library definitely works with GKE, you need to figure out how to construct the right client config in memory if you want to go that route.

Closing since there's nothing really to do here. Please re-open if you need more info.

**Comment by thesayyn** [comment]
Then a helper function or an example would be good.

**Comment by JohnLBergqvist** [comment]
@brendandburns This most definitely does not work with GKE cluster from a kubeconfig file. 
Here is how i'm setting up the object:
```
  config.loadFromOptions({
    apiVersion: 'v1',
    clusters: [{ cluster: { 'certificate-authority-data': masterAuth.clusterCaCertificate, 'server': `https://${GKE.endpoint}` } }],
    contexts: [{ context: {} }],
    users: [{ user: { 'auth-provider': { config: { 'access-token': authToken.credentials.access_token } } } }],
  });
```
Now this config (albeit minimal) works fine in the pre-merger kubernetes-client, however now I get the `Error: unable to verify the first certificate` after attempting to make an authenticated request.
