### ISSUE TITLE
deletePersistentVolume method bad response

### ISSUE THREAD

**Issue by pjir** [kubernetes-client/javascript#263]
**deletePersistentVolume** method returns body **V1PersistentVolume** and it should return **V1Status**.

    deletePersistentVolume(name: string, pretty?: string, body?: V1DeleteOptions, dryRun?: string, gracePeriodSeconds?: number, orphanDependents?: boolean, propagationPolicy?: string): Promise<{
        response: http.IncomingMessage;
        body: V1Status;
    }>;

The same for other delete methods, for example deleteNamespace. 

`
...
Request {
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        method: 'DELETE',
....

body:
   { kind: 'PersistentVolume',
     apiVersion: 'v1',
     metadata:
...
`

**Comment by brendandburns** [comment]
@pjir it actually returns both, depending on the situation (async delete vs delete completed).

Swagger 2 (current spec) doesn't support multi-return so we have to live with this, Swagger 3 will support it (and eventually we'll get there).

I'm going to close this since there's nothing that can be done in this library.
