### ISSUE TITLE
Shutdown watch without reason

### ISSUE THREAD

**Issue by yangukmo** [kubernetes-client/javascript#301]
Hi. I'm using watch to monitor Pods.

```js
const k8s = require('@kubernetes/client-node')

const kc = new k8s.KubeConfig()
kc.loadFromDefault()
const watch = new k8s.Watch(kc)

const callback = (phase, obj) => {
  ...
}

const done = (err) => {
  console.error(err)
}

watch.watch('/api/v1/namespaces/default/pods', {}, callback, done)
```

I deployed this as a Docker and it is being restarted every hour without any error message.
I don't know what the problem is.

**Comment by brendandburns** [comment]
Watches use a long standing network connection. Somewhere in the network path the watch is timing out or getting disconnected.

In general, watch shouldn't be treated as persistent, you should wrap your call to watch in a loop.

Or (preferred) you should use a more complete interface like a watch cache or informer:

https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/informer/informer.ts

**Comment by yangukmo** [comment]
@brendanburns Thank you for your answer. :+1:
The above issue is not occurring because of the change to informer.
But periodically, all Pods are generating 'updated' events.
There have been no changes, but I wonder why they are called.

**Comment by brendandburns** [comment]
The update events occur when the watch drops and the informer re-connects. The reason for this is that it is possible that there were changes between the watch that stopped and the reconnect that may otherwise be missed.

So the informer first lists all objects, and then watches each time the watch reconnects.

Thus you should expect (and handle) updates for objects that already exist.
