### ISSUE TITLE
Example cluster configuration documentation update

### ISSUE THREAD

**Issue by brentbahry** [kubernetes-client/javascript#342]
1. I found the user object needs a `username` property to successfully authenticate via `CoreV1Api.loadFromOptions`
2. May be worth including an https example; my use case, which I imagine is common, is connecting to a production k8s (GKE). I had to dig around to determine that certificate authority data needs to be passed into the client (got error 'unable to verify the first certificate'), and additionally there is no tsd or doc indicating that ca data can be passed into the client via a `caData` property on the user object when calling `CoreV1Api.loadFromOptions`

**Comment by brendandburns** [comment]
Hrm, what you are doing isn't the suggested happy path. Generally people load from a kubeconfig file (e.g. `$HOME/.kube/config`)

The happy path way that people load is using `loadFromDefault()` and is used in all of the examples (e.g. https://github.com/kubernetes-client/javascript/blob/master/examples/example.js#L4)

Or if you are loading inside a cluster, you should use `loadFromCluster` as shown here:
https://github.com/kubernetes-client/javascript/blob/master/examples/in-cluster.js#L4

Are there documentation improvements we could add to help you find those functions?

Thanks!

**Comment by brentbahry** [comment]
I saw there to be value in the programmatic api, is there a pitfall I should be aware of? I'm using it currently.

<img width="1487" alt="Screen Shot 2019-09-15 at 12 30 18 PM" src="https://user-images.githubusercontent.com/1676613/64926653-c9215200-d7b4-11e9-9950-1d3e31ba6d8c.png">

**Comment by brendandburns** [comment]
It's fine to create it programattically, it's just an advanced use case where we'd expect that a user knew enough about kubernetes configuration objects to know that they needed to include the `caData` etc.

In general, if you already have a `kubeconfig` file you're better off using the file loader config rather than constructing it programatically, the programatic support is there for people who are dynamically generating a config in code.

If you want to send a PR to improve the programattic example that'd be great.

Thanks

**Comment by brendandburns** [comment]
Closing, since I don't think there is additional information to be provided here.
