### ISSUE TITLE
Use named arguments over a long list of undefineds

### ISSUE THREAD

**Issue by entropitor** [kubernetes-client/javascript#385]
It would be nice if named arguments in the form of an object are used instead of many arguments that can be undefined. It's really hard to know which argument you are actually providing.

e.g.

```javascript
k8sApi.patchNamespacedPod('my-pod', 'default', [], undefined, undefined, undefined, undefined, {headers: {...}})
```

```javascript
k8sApi.patchNamespacedPod({
  podName: 'my-pod', 
  namespace: 'default', 
  body: [], 
  requestOptions: {headers: {...}}
})
```

With the above it's still a bit clear but if there is a boolean in there somewhere you have no idea what that boolean does without a comment. Named arguments through objects would help a lot

**Comment by brendandburns** [comment]
Unfortunately, this is all code generated by the openapi-code generator:

https://github.com/OpenAPITools/openapi-generator

There has been discussion/work to create a more fluent API, see:

https://github.com/kubernetes-client/javascript/pull/244

I'm going to close this issue, partially because fixes would need to be in the code generator, and partially because there's the open PR for fluent fixes which is a better place for discussion.

If you would like to reopen please use the /reopen command in a comment.
