### ISSUE TITLE
Stop watching or informing?

### ISSUE THREAD

**Issue by xogeny** [kubernetes-client/javascript#402]
I cannot figure out how to "unsubscribe" to either the informer or the watcher?

Informer has a `start()` method, but no `stop()` method.

The watcher seems to return a promise to a request (although the type definitions do not say that, only the example).  However, for my code that promise never gets resolved so that I can `req.abort()` the watcher.

The use case here is one where you are waiting for a specific update (*e.g.,* a given pod completed) and then you want to terminate watching.  It is quite unclear how to do this.

Armed with that knowledge, I *think* I could probably write some code that used these functions internally to formulate a higher level `rxjs` `Observable` out of all this.  The ability to unsubscribe is kind of the last piece in the puzzle.

**Comment by unfor19** [comment]
I reported almost the same thing here - #401 

I also can't resolve the `req.abort()` with `watch` ... @brendandburns any thoughts about this one ? ...

**Comment by mtiller** [comment]
I've created code to use the Watch to feed an `rxjs` `Subject` and then that allows clients to subscribe to that `Subject` to track updates.  Unfortunately, I get the although I'm not aborting the underlying request, it seems like something is because the final callback for `Watch` is getting invoked without an error.  I know the watch has some limits on how long it runs.  So I suspect that is what's going on.  But the whole system seems ripe for race conditions and problems with various error contingencies.  I may try the informer interface.  But there we have the same issue of not having a reliable way to terminate it (as far as I can tell).

**Comment by mtiller** [comment]
I looked at the informer code a bit and it seems like a relatively simple solution is possible.  Every time a `Watch` is created, the returned `Promise<Request>` could be stored.  A separate `stop` method could be written that awaits the request and then triggers `req.abort()`.  It then further sets an internal flag indicating the informer is stopped so that the `doneHandler`, when invoked, won't initiate a new `Watch`.  That seems like all that would be required.  Would a PR be accepted for such functionality?

**Comment by patrickschur** [comment]
@xogeny I found the problem. Short answer: Just update the version of `@kubernetes/client-node` to `0.11.1` and you are good to go. For more information please have a look at [my comment](https://github.com/kubernetes-client/javascript/issues/401#issuecomment-581320202) on the issue #401.

**Comment by andrewrynhard** [comment]
Although there may be a solution for `watch`, I don't see one for `informer`.

**Comment by patrickschur** [comment]
@andrewrynhard There is no `stop()` method but there is an `off()` method to unsubscribe from events.

If you run the following example there will be no output. But when you remove the line with the `off()` method there is an output. Hopefully this helps.
```js
const k8s = require('@kubernetes/client-node');

const kc = new k8s.KubeConfig();
kc.loadFromDefault();

const k8sApi = kc.makeApiClient(k8s.CoreV1Api);

(async () => {
    const listFn = () => k8sApi.listNamespace();
    const informer = k8s.makeInformer(kc, '/api/v1/namespaces', listFn);

    const addCb = (obj) => { console.log(`Added: ${obj.metadata.name}`); };

    informer.on('add', addCb);
    informer.off('add', addCb); // unsubscribe from event

    await informer.start();
})();
```

**Comment by andrewrynhard** [comment]
@patrickschur Thanks. I might be able to use this, however, I still think that being able to stop the informer would be good to have. I will give this a whirl in the mean time 👍.

**Comment by mtiller** [comment]
The issue with `off` vs `stop` is that you'll still have a dangling request and the Javascript event loop will still be waiting for something.  This is important in testing.  When running tests (at least with `jest`), you'll get a bunch of warnings/errors from `jest` if you haven't cleared out all pending asynchronous sources.  When it comes to tests, I don't want that kind of stuff obscuring real issues.

**Comment by unfor19** [comment]
@mtiller I've added a full example on how to use the watch class - #401 . Check it out, it might fit your jest example.

I know it's not informer, but still, it's a good start

**Comment by eliecharra** [comment]
@mtiller Did you finally manage to find a solution for informer in jest context ?

**Comment by mtiller** [comment]
Looking back, it appears I didn't figure anything out.  It seems I'd have to create my own informer implementation.  I think it could definitely be done.  The way the current informer restarts itself after connections are lost might make it tricky.  But I'm pretty confident it could be done.  I just haven't returned to that aspect of things.  If I do get back to it, I'll try and create something.  I made a note in my code so that if I ever come back to this I know to update this issue.

**Comment by stavalfi** [comment]
any test runner can't work with it AND also we can't write CLI tools as well for the same reason.

closing the informer is pretty valid scenario. 

is there any progress on this?
