### ISSUE TITLE
Security Scanning failing due hard-coded Credentials in config.js

### ISSUE THREAD

**Issue by sureshkallem** [kubernetes-client/javascript#468]
We ran a security scan to identify the vulnerabilities and identified the 4 issues related to hard-coded credentials.
1. /client-node/dist/config.js 121
2. /dist/config_test.js
3. /dist/config_test.js 432 8/3/20
4. /dist/config_test.js 441 8/3/20

Can we resolve those issues?

**Comment by drubin** [comment]
HI @sureshkallem

Thanks for the report, what tool did you use to scan the package so we can try to reproduce the exact issues?

I am assuming you are testing the npm package and not the source?

`config_test` files are test files, this is pretty standard as we need to write unit tests, we can however exclude them from the final npm package which should be the case.

Regarding `config.js` I did a quick look through the `config.ts` file and it doesn't contain any hardcoded credentials, could you maybe point me at the exact issue?

**Comment by brendandburns** [comment]
I'm wondering about your scanning of the `js` files also. Those files are generated by the typescript compiler, probably the right thing to do is to scan the `ts` files, not the `js` files.

But definitely anything in unit test files should be excluded since the credentials are both bogus, and also used for testing purposes so they're needed.

As @drubin says more details about the problem and how to reproduce it in `config.[js|ts]` would be useful.

**Comment by brendandburns** [comment]
Closing this due to no response. Please use the `/reopen` command if you need further assistance.

**Comment by sureshkallem** [comment]
Hi,
Thanks for your email.

We are using veracode for scanning and we are getting the errors in
config.test.js file.

Thanks,
Suresh Kallem
