### ISSUE TITLE
kubectl apply equivalent

### ISSUE THREAD

**Issue by lakshmanpasala** [kubernetes-client/javascript#470]
Is there a `kubectl apply -f file.yaml` equivalent for this client?

**Comment by brendandburns** [comment]
`kubectl apply -f file.yaml` operates on the client side. There is experimental server-side apply that you can access by using the `patch*` set of API calls and a content-type of `apply-patch+yaml`

But if what you really want to do is just replace the content (rather than tracking changes like apply does) then you can just use the `replace*` set of API calls (e.g. `CoreV1.replaceNamespacedPod(...)`)

**Comment by rdiaz82** [comment]
I'm using this example for it: [https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/apply/apply-example.ts](https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/apply/apply-example.ts) and it works pretty smooth

**Comment by lakshmanpasala** [comment]
Yeah, found this to work well. Also, I use kubectl verbose `--v=8` to see HTTP requests for our custom resource definitions and make respective changes.

**Comment by brendandburns** [comment]
I'm going to close this issue since I think it is resolved. Please use `/reopen` if more assistance is needed.
