### ISSUE TITLE
How to scale?

### ISSUE THREAD

**Issue by phantomlsh** [kubernetes-client/javascript#475]
Can you provide a simple example of scaling deployments?

**Comment by brendandburns** [comment]
You need to use `getNamespacedDeployment(...)` to get the Deployment object, then update the number of replicas in the spec, then use `replaceNamespacedDeployment(...)` to update it in the API.

There's no code example of this right now, but we'd be happy to take a PR adding one.

**Comment by phantomlsh** [comment]
@brendandburns 

I use `const k8sApi = kc.makeApiClient(k8s.AppsV1Api);` cause the deployment itself is applied with apiVerision `apps/v1`

But it turns out that
```
TypeError: k8sApi.getNamespacedDeployment is not a function
```

**Comment by phantomlsh** [comment]
Oh ok, I figure out that it is `listNamespacedDeployment()` with `k8s.CoreV1Api`

**Comment by brendandburns** [comment]
Sorry, I should have said `readNamespacedDeployment(...)` instead of `getNamespacedDeployment(...)`

Listing works too, but you can use `read` if you only need to get one of them.

Closing since I think the question is answered, feel free to use the `/reopen` command or open a new issue if you need further assistance.
