### ISSUE TITLE
exec.Exec() method throw (node:2220468) [DEP0123] DeprecationWarning using minikube

### ISSUE THREAD

**Issue by flacatus** [kubernetes-client/javascript#512]
Hi!
Currenlty we are using kubernetes client in one of our project and when we tests our product in minikube... 
exec.Exec() methods throw `(node:2220468) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.`

![image](https://user-images.githubusercontent.com/59865209/94174994-50100c80-fe96-11ea-8562-485bf7d22611.png)

Can you help me to understand the error? I'll paste my code.

```javascript
  async execCommandInPod(namespace: string,podName: string, containerName:string): Promise<void> {
    try {
      const containerExec = new Exec(KubeHelper.KUBE_CONFIG)
      const tasks = [
        'ls',
      ]

      await containerExec.exec(namespace, podName, containerName, tasks, process.stdout as Writable, process.stderr as Writable, process.stdin as Readable, true)

    } catch (e) {
      throw this.wrapK8sClientError(e)
    }
  }
```

**Comment by brendandburns** [comment]
This is coming because you are connecting to an IP address instead of a DNS name.

It looks like it is resolveable by not setting the `servername` property in the tls options

(https://github.com/brianc/node-postgres/pull/1890/files)

But we'll have to investigate how to do that. For now, it's harmless.
