### ISSUE TITLE
Is there a type in this repo for the result of "kubectl get pods -o json ..."

### ISSUE THREAD

**Issue by guyellis** [kubernetes-client/javascript#545]
This is really Stack Overflow question but not sure if you have a presence there? Happy to move the question there. LMK.

Context: The enterprise does not allow access to the Kubernetes API so much of the functionality in this module is not available to me. I can however run `kubectl` and get results back.

So I'm using `import { exec } from 'child_process'` and executing this pattern:

`kubectl get pods -o json -n <my-namespace> --context=<my-context>`

and getting back something that I can `JSON.parse()` and get well structured data from that I'm able to use.

My question: Is there a TypeScript type in this library that matches the output from `kubectl get pods -o json ...` that I can use against the data that I get back from `JSON.parse()`?

**Comment by brendandburns** [comment]
Yes, there are a bunch of objects for all of the kubernetes objects, have a look here:

https://github.com/kubernetes-client/javascript/tree/master/src/gen/model

However, it's weird that kubectl works and this library doesn't. They both run HTTP requests to talk to the kubernetes APIserver so from a network firewall perspective it's hard to understand why one would work and one wouldn't.

It's possible that if there is a proxy in between that `kubectl` does a better job talking to the proxy than this library does, if that's the case I'd love more details so that we can improve things.

I think this library aspires to be usable wherever `kubectl` works.

**Comment by guyellis** [comment]
@brendanburns - thanks. Not sure why my earlier searching in the repo didn't show those up.

I completely agree with your comments and would also much rather use the API than doing a "shell exec" and parsing the JSON. I've spoken with the team and they're adamant that for security reasons they don't want us using the API. I'm sure that it would be relatively easy to work out how to use the same credentials that `kubectl` is using to access the API and create a bridge/proxy to enable the use of this client module but at the end of the day that would be circumventing what they want to prevent so I'm not going to do that. I will, however, continue to have this conversation with them and hopefully one day we can get approved access.

I don't actually understand how security is improved by limiting access to the API as `kubectl` has access anyway.
