### ISSUE TITLE
Angular support

### ISSUE THREAD

**Issue by sundarvc** [kubernetes-client/javascript#556]
Hi team,

Does the javascript library work with the latest angular framework ?
I am getting many build issues e.g.

ERROR in ./node_modules/jose/lib/jwe/decrypt.js
Module not found: Error: Can't resolve 'zlib' in '/Users/i821932/work/SSC/POC/kyma-luigi-ui/node_modules/jose/lib/jwe'

ERROR in ./node_modules/jose/lib/jwe/encrypt.js
Module not found: Error: Can't resolve 'zlib' in '/Users/i821932/work/SSC/POC/kyma-luigi-ui/node_modules/jose/lib/jwe'

ERROR in ./node_modules/minizlib/index.js
Module not found: Error: Can't resolve 'zlib' in '/Users/i821932/work/SSC/POC/kyma-luigi-ui/node_modules/minizlib'

ERROR in ./node_modules/minizlib/constants.js
Module not found: Error: Can't resolve 'zlib' in '/Users/i821932/work/SSC/POC/kyma-luigi-ui/node_modules/minizlib'

ERROR in ./node_modules/request/request.js
Module not found: Error: Can't resolve 'zlib' in '/Users/i821932/work/SSC/POC/kyma-luigi-ui/node_modules/request'

**Comment by brendandburns** [comment]
Assuming you mean angular + browser, then the answer is no. This library only works in nodejs.

In general, accessing Kubernetes API servers from the browser is tricky because most kubernetes servers have their own certificate authority and your browser won't accept an SSL connection with the api server.
