### ISSUE TITLE
loadFromString produces fails to validate yaml

### ISSUE THREAD

**Issue by Nokel81** [kubernetes-client/javascript#557]
Current Behaviour:
If you pass a string to `loadFromString` that is not the expected yaml format (for instance is a string representing a path to a file) the function happily plows through assigning all the fields to `[]`.

Expected Behaviour:
Some form of validation occurs in this case, and errors thrown if something unexpected comes up

**Comment by brendandburns** [comment]
I'm not sure what the expectation is here. The YAML didn't throw an exception, how can we determine if it was incorrect?

If you have ideas and want to implement something we'd be happy to consider a PR.

**Comment by Nokel81** [comment]
So a plain string is considered valid YAML, however it isn't the sort of thing that should pass validation (imo). This would only be wrong if this package shouldn't do that sort of validation.

Namely: I think that the following code should throw an error.

```js
const kc = new Kubeconfig()
kc.loadFromString("/accidentally/a/path")
```

**Comment by drubin** [comment]
I think the issue here is in the naming and expectations 

`loadFromString` seems to me you are loading the config from a string-based config (json or yaml)

Maybe we can add another more explicit API which is load from file 

```js
const kc = new Kubeconfig()
kc.loadFromFile("/accidentally/a/path")
```

I suspect we might even have the above (but naming might be different)

I agree with @brendandburns here and saying this type of logic is incredibly hard to detect and it could result in even more confusion if we try an make a single function that handles all these usecases.

**Comment by Nokel81** [comment]
There is `loadFromFile` already. I thought that some simple validation that the yaml passed in to `loadFromString` is of the "correct shape" would be useful.

**Comment by brendandburns** [comment]
I think that the best thing to do is to probably add some logic that is a test like:

`isEmptyConfig(config)` which tests if the config is empty (e.g. no clusters, no users, etc)

Then you could do something like:

```js
config = loadFromString(...);
if (config.isEmptyConfig()) {
   // your error handling logic here
}
```

We'd be happy to take a PR adding that test.

**Comment by Nokel81** [comment]
Bump, I still plan on working on this.
