### ISSUE TITLE
Issue with `exec` command

### ISSUE THREAD

**Issue by LiorRabin** [kubernetes-client/javascript#598]
I'm trying to run the following code and I can't get the `$(which bundle)` to work.
When I use `bin/bash` as the command and open the terminal in the pod, it works and prints the command properly.
Any suggestions?

```
  const cluster = getClusterClient(env, region)
  const exec = new k8s.Exec(cluster)
  const rl = await getReadLine()
  try {
    await exec.exec(
      pod.metadata.namespace,
      pod.metadata.name,
      pod.spec.containers[0].name,
      ['/bin/bash', '-c', 'export BUNDLE_CMD=$(which bundle); echo $BUNDLE_CMD'],
      rl.output, process.stderr, rl.input, true)
  } catch (error) {
    logger.error(error)
    rl.close()
  }
```

**Comment by brendandburns** [comment]
We need more details to debug. What doesn't work? What error are you seeing?

**Comment by LiorRabin** [comment]
I just get an empty string in `BUNDLE_CMD` with the above example, and when I just `/bin/bash` into the pod and run the same command `export BUNDLE_CMD=$(which bundle); echo $BUNDLE_CMD` I get the desired result

**Comment by brendandburns** [comment]
Ok, so it sounds like the command is executing correctly, it's just not producing the expected output. Given that it appears the client is working correctly (the command is executing, returning 0 and producing some output) I think debugging is this is beyond the scope of the library.

If I had to guess, I'd bet that the `$PATH` variable is different in the two different environments (probably because bash is loading differently when it has a tty or not) but debugging at this level is beyond the scope of this library.

I'm going to close this issue. If you do find that it seems to be a problem with the client please use `/reopen` to reopen the issue and add more details.
