### ISSUE TITLE
missing deleteCollectionNamespacedService?

### ISSUE THREAD

**Issue by oliverkane** [kubernetes-client/javascript#603]
I wasn't able to locate a method called ``` deleteCollectionNamespacedService ``` which hangs off of the ``` CoreV1Api ```.  There seems to be corresponding methods for similar operations.  Is this oversight in this client project, or is that not supported in the k8s api?

Eg:  I can

```javascript
await appsV1Api.createNamespacedDeployment()
await appsV1Api.deleteCollectionNamespacedDeployment(k8sNamespace) 
```

And I can

```javascript
await coreV1Api.createNamespacedService()
```

But I cannot

```javascript
await coreV1Api.deleteCollectionNamespacedService()
```

**Comment by oliverkane** [comment]
Hm, researching further, I think I may have answered my own question.  There doesn't appear to be a delete collection operation for services. Curious. I wonder why that's the case?

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#-strong-write-operations-service-v1-core-strong-

**Comment by brendandburns** [comment]
All of this stuff is generated from the Kubernetes OpenAPI (both the docs and this client), if there's a gap, it's probably in that swagger.

(that said, this is the first request for that support that I've seen)

I'm closing this issue because there's not much for us to do here. If there is a problem, it should be fixed in the Kubernetes OpenAPI and then it will flow to this client.

The spec is here:
https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/swagger.json

**Comment by oliverkane** [comment]
@brendanburns, you're quite correct, there doesn't appear to be a method for this.  The work around is fairly simple for me, since i'm not dealing with a large enough amount of objects that iterating can't just be used. I'll ask upstream. Thank you for taking the time for a reply.
