### ISSUE TITLE
No release for more then a month while having new commits in the master

### ISSUE THREAD

**Issue by dkontorovskyy** [kubernetes-client/javascript#625]
**Describe the bug**
There've been multiple commits that might fix some issues in Informers, but they were not yet released to `npm`
Could you release, please? 🤗 

** Client Version **
`0.14.0`

**Expected behavior**
Seeing new releases after merge

**Comment by brendandburns** [comment]
All of the major informer fixes are in `0.14.0` there are a couple of minor improvements (some new event handlers, the ability to stop an informer) that are more recent. Is there a specific change that you are looking for?

I'll see about getting a `0.14.1` released, but if you are facing a significant issue w/ informers, it probably won't be fixed by the new release (and please file an issue with details of the problems you're seeing)

**Comment by dkontorovskyy** [comment]
It's all related to https://github.com/kubernetes-client/javascript/issues/589. We've been trying to implement a workaround using timeouts (https://github.com/kubernetes-client/javascript/issues/596#issuecomment-793121295), but we are missing the stop function (https://github.com/kubernetes-client/javascript/issues/596#issuecomment-792372393).

Do I need to create a new issue? Most of it is described in here (https://github.com/kubernetes-client/javascript/issues/596#issuecomment-801218411)

**Comment by brendandburns** [comment]
Thanks for the info, I just pushed `0.14.1` with the stop fixes.
