### ISSUE TITLE
V1ServicePort with wrong type for targetPort

### ISSUE THREAD

**Issue by Saeger** [kubernetes-client/javascript#666]
**Describe the bug**
The "targetPort" type is defined as "object" while the possibility of values can be both number and string.
With this said, you can't set a type for a variable and fill targetPort with a number the way it's implemented.
"Type 'number' is not assignable to type 'object'.ts(2322)"

** Client Version **
`0.14.3`

** Server Version **
`1.18.0`

**To Reproduce**
Define a variable of type V1Service and try to make the specs for ports.

**Expected behavior**
The type definition could be defined as number | string since both are supported.

** Example Code**
`      ports: [
        {
          name: 'http',
          port: 80,
          targetPort: 3000,
          protocol: 'TCP',
        },
      ],`

**Environment (please complete the following information):**
 - OS: OSX
 - NodeJS Version 14

**Comment by brendandburns** [comment]
Officially, the targetPort is an IntOrString so we need to implement special handlingwhich currently doesn't exist.

**Comment by Saeger** [comment]
@brendanburns where should I start looking and see if I could help with a fix ?

**Comment by brendandburns** [comment]
@Saeger thanks for offering to help.

We haven't done this for Javascript before, so it's likely to be a little rocky, but here's what (I think) you need to do.

We need to add `typeMappings` and `importMappings`, similar to this one in the Java client:
https://github.com/kubernetes-client/gen/blob/master/openapi/java.xml#L96

To the Javascript client config:
https://github.com/kubernetes-client/gen/blob/master/openapi/typescript.xml

Then you need to regenerate the client:
`npm run generate`

This code should not compile because it will be missing the `IntOrString` type, so then you'll need to add `custom.ts` (or somesuch) and define the `IntOrString` class in that file.

As I mentioned, complicated, please feel free to ping this issue if you try and see errors!

**Comment by alex-bezek** [comment]
@brendandburns thanks for pointing me to this issue, I've created a couple of pull requests which I think address the issue:
* https://github.com/kubernetes-client/javascript/pull/741
* https://github.com/kubernetes-client/gen/pull/213

**Comment by brendandburns** [comment]
I have just pushed an `0.16.1` release to npm that contains a fix for IntOrString types. Many thanks to @alex-bezek for sending the PRs.
