### ISSUE TITLE
PodDisruptionBudget types are incorrect

### ISSUE THREAD

**Issue by maxweisel** [kubernetes-client/javascript#675]
**Describe the bug**
V1beta1PodDisruptionBudgetSpec defines `minAvailable` and `maxUnavailable` as type `object` but the spec accepts string or number.

** Client Version **
e.g. `0.14.3`

** Server Version **
e.g. `1.17.17`

**To Reproduce**

Try to compile the following:

```
const kubeconfig = new Kubernetes.KubeConfig()
const kubernetesPolicy = kubeconfig.makeApiClient(Kubernetes.PolicyV1beta1Api)
kubernetesPolicy.createNamespacedPodDisruptionBudget({
  apiVersion: 'policy/v1beta1',
  kind: 'PodDisruptionBudget',
  metadata: {
    name: 'test',
  },
  spec: {
    minAvailable: 2,
    selector: {
      matchLabels: {
        app: 'test'
      }
    }
  }
}
```

**Expected behavior**
I'd expect the typescript compiler to allow this. However, instead it complains that `minAvailable` is not of type `object`

**Environment (please complete the following information):**
 - OS: Mac
 - NodeJS Version 14 LTS

**Comment by brendandburns** [comment]
This is a duplicate (though for a different field) of #666 

The net-net is that we don't support any fields of `IntOrString` types very well.

Closing in favor of #666, there are instructions in that issue about how we need to approach fixing this, if you have time, otherwise I will get to it eventually.
