### ISSUE TITLE
Status callback is not called every time for `exec`

### ISSUE THREAD

**Issue by indiejames** [kubernetes-client/javascript#714]
**Describe the bug**
The `exec` function does not seem to call the status callback function consistently. Sometimes it gets called, mostly it does not. The actual status of the executed command does not seem to influence this.

** Client Version **
`0.15.1`

** Server Version **
`1.21.2`

**To Reproduce**
Execute an `exec` call with a status callback function.

**Expected behavior**
I expect to to see the callback function called every time the `exec` function is called, regardless of whether or not the executed command exited with a status code 0 or not.

** Example Code**
```TypeScript
await exec.exec(
    'argo',
    'myPod',
    'worker',
    ['exit', '1'],
   process.stdout as stream.Writable,
    process.stderr as stream.Writable,
    process.stdin as stream.Readable,
    true,
    (status: k8s.V1Status) => {
      log.debug(`SIDECAR STATUS: ${JSON.stringify(status, null, 2)}`);
    },
  );
```

**Environment (please complete the following information):**
 - OS: macOS Catalina
 - NodeJS Version: v12.22.4
 - Cloud runtime: N/A (local development using Kubernetes from Docker Desktop for Mac)

**Additional context**
I have only seen the callback called for errors, but even this is inconsistent.

**Comment by dominic-p** [comment]
I'm seeing very similar behavior in my testing.

@indiejames were you ever able to track down why this was happening? In my experience, if I don't provide a stdin stream, I get output and the status callback is called reliably. If I do provide stdin, the WebSocket connection closes after the input stream ends, but the status callback is never called.

As far as I can tell, the status callback only gets called if the `handleStandardStreams` function returns non-null. That only happens if we get a message on the StatusStream. Whenever I pass in a stdin stream, I never get a message on the StatusStream and so the status callback is never called.

I just don't know what is responsible for generating messages on the StatusStream and why it isn't doing its job.

**Comment by imathews** [comment]
I want to add that I'm also observing the same behavior as @dominic-p on the latest version `0.20.0`

@brendandburns, should this issue be re-opened? I don't see anywhere else tracking this exec bug...

**Comment by indiejames** [comment]
I just worked around this by having my service issue a throw away 'priming' exec call to the pod when it starts up, so that subsequent calls work correctly.

**Comment by imathews** [comment]
Yea I ended up implementing a similar approach. However, this issue does seem to rear its head after a period of inactivity (several hours in my case). So it's a bit tricky to know when the 'priming' exec call is needed, and this all feels a bit hacky...

**Comment by mstruebing** [comment]
If this is still an issue I think we should reopen it.
There is a small chance that this will be automatically fixed in the `release-1.x` branch.
You can reopen an issue by issuing a comment with `/reopen`.

**Comment by imathews** [comment]
@mstruebing I'll try to test this as bandwidth allows (takes a bit of time to recreate on our local setup), but in the interim I'll reopen since this remains an issue in the latest release.

/reopen

**Comment by imathews** [comment]
Actually will need @indiejames or @mstruebing to reopen
