### ISSUE TITLE
Please create GitHub releases for new versions

### ISSUE THREAD

**Issue by Legion2** [kubernetes-client/javascript#740]
It is realy hard to track the releases of this project, because there are no releases or tags published in GitHub (in the past there were releases published to GitHub). I just realized there is a new version, because dependabot updated the dependency in our project.

**Comment by brendandburns** [comment]
fwiw, there are git tags pushed for every release:
https://github.com/kubernetes-client/javascript/tags

Github releases have been more inconsistent because they have to be hand-curated.

I'd gladly take PRs to add automation that creates GitHub releases. The release script is here:
https://github.com/kubernetes-client/javascript/blob/master/push-package.sh

So if you wanted to send a PR to improve that script to also create GitHub released, that would ensure that we always create GitHub releases.
