### ISSUE TITLE
Fix vulnerability issue reported by Trivy

### ISSUE THREAD

**Issue by eagleweb** [kubernetes-client/javascript#742]
**Describe the bug**
Trivy security scan reports that `json-schema` has critical vulnerabilities related to Prototype Pollution.

** Client Version **
`0.16.1`

**To Reproduce**
run "yarn audit" or "trivy fs ." 

<img width="970" alt="Screenshot 2021-11-22 at 16 16 57" src="https://user-images.githubusercontent.com/15260354/142877113-fb2a7506-1384-4c58-b1f1-6b9e61d0b43e.png">

<img width="644" alt="Screenshot 2021-11-22 at 16 15 09" src="https://user-images.githubusercontent.com/15260354/142877346-687d8ae6-27c9-47fe-a169-82dc4ec38a30.png">

**Comment by brendandburns** [comment]
Feel free to send a PR changing the revision for json-schema, I don't believe this code is used in this library in such a way as to cause a security issue, but I have no objections to reving the version, assuming tests pass.

**Comment by eagleweb** [comment]
Thanks, @brendandburns for your reply.
As I can see you are using the `request` package which causing this issue and it's deprecated, maybe it's better to replace this package with a new one?
Here some variants - [Alternative libraries to request](https://github.com/request/request/issues/3143)

**Comment by brendandburns** [comment]
@eagleweb there is a large discussion of the challenge of replacing `request` in the issue here:

https://github.com/kubernetes-client/javascript/issues/414

The tl;dr; is that replacing request would involve using a different generator, which would result in a different shaped client, which would be a major breaking change.

For this specific security concern, I think we should just try updating the vulnerable library, since I'm fairly certain we don't use it anyway.

**Comment by brendandburns** [comment]
The switch to fetch is now being tracked in #754.
