### ISSUE TITLE
error TS1192: Module '"http"' has no default export, esModuleInterop

### ISSUE THREAD

**Issue by arshad-akra** [kubernetes-client/javascript#751]
- im getting these errors directly upgrading from 0.15.1 to 0.16.1 
- this is similar to [This](https://github.com/apollographql/apollo-server/issues/1189) issue on apollo-server

```
node_modules/@kubernetes/client-node/dist/gen/api/wellKnownApi.d.ts:13:8 - error TS1192: Module '"http"' has no default export.

13 import http from 'http';

node_modules/@kubernetes/client-node/dist/gen/model/models.d.ts:2:8 - error TS1259: Module '"/home/arshad/Code/uphabit/backend/node_modules/@types/request/index"' can only be default-imported using the 'esModuleInterop' flag

2 import localVarRequest from 'request';
```
### attempted fixes 
- setting `esModuleInterop: true` is throwing 300 errors at all old `import * as ....`  and changing all those is not feasible 

- is there anything else that needs to be set or any other way to overcome this ?
Thanks

**Comment by brendandburns** [comment]
This is related to the changes here:
https://github.com/kubernetes-client/javascript/pull/727

Which were introduced as part of the `0.16.x` release.

Specifically:
```"esModuleInterop": true```

is now set in the tsconfig.

Please see the discussion here about this flag:

https://github.com/microsoft/TypeScript/issues/41139

And here:

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-from-commonjs-modules-with---esmoduleinterop

I think we are going to retain this flag as part of this library going forward, since that flag appears to be headed to be the default option in typescript as well.

**Comment by brendandburns** [comment]
If there is any action to take on this library to improve things, please let me know.
