### ISSUE TITLE
How to set timeout for global

### ISSUE THREAD

**Issue by rpig** [kubernetes-client/javascript#815]
I have two questions:
1、can we support the global k8s timeout set，now we just can set timeout by every function，this is so trouble，like this:
```js
nodes = await k8sApi.listNode(
        undefined,
        undefined,
        undefined,
        undefined,
        `xxx in xxx`,
        undefined,
        undefined,
        undefined,
        5000
      );
```
if we can set it global by `makeApiClient` may be better。

2、I want set the http request timeout is disable，now only can set k8s apiserver timeout, we can passthrough the options to the request sdk so can support http request timeout。
<img width="748" alt="image" src="https://user-images.githubusercontent.com/6789139/171345944-9a98a42f-164c-40df-96d6-f4246c33fbde.png">

**Comment by brendandburns** [comment]
All of this code is generated by the open api code generator (https://github.com/OpenAPITools/openapi-generator) so any changes need to be done there rather than in this code.

There's also a plan in place to switch to a different code generator (since request is deprecated).

The net of these two things is that these modifications are unlikely to happen in the near term, but I will leave this issue open as a reminder if we get a chance to do this later.

**Comment by brendandburns** [comment]
In investigating #817 I actually realized this is possible using the `Interceptor` pattern, you can look at the interceptor here:

https://github.com/kubernetes-client/javascript/blob/master/src/gen/model/models.ts#L1872

And add that to the `k8sApi` object via `k8sApi.addInterceptor(...)`
