### ISSUE TITLE
Get logs as a string

### ISSUE THREAD

**Issue by jeffersonbenson** [kubernetes-client/javascript#906]
Hey all!

I'm trying to decipher how to return the last 25 lines of the logs of my pod to a parent function. So far I've begun the process of learning Streams (I'm a beginner in JS development) but I'm hung up trying to get the stream into something a bit more "static" so I can insert it into a JSON document I'm composing. 

Is there a vanilla method I'm missing that will take the stream data and just output a string I can return? I'm using the log.log from [follow-logs.js](https://github.com/kubernetes-client/javascript/blob/master/examples/follow-logs.js) but I believe there's a fundamental understanding I'm not grasping. Any insight would be greatly appreciated. Thanks!

PS Apologies for using this format to ask for help. I wasn't able to find any other medium for support. If there is a better place to ask this, please let me know 😁

**Comment by brendandburns** [comment]
Stack overflow is your friend:
https://stackoverflow.com/questions/10623798/how-do-i-read-the-contents-of-a-node-js-stream-into-a-string-variable

Basically starting from the `follow-logs.js` example, every time that a chunk is passed to the `on('data', ....)` you should append that chunk into an array and then you will be able to process that array of chunks.

Note that the follow logs example is purposefully intended to be a long-running operation (the example times out after 5 seconds, but if you remove that timeout it will just hang) so if you want to stream the results into a GUI somehow, then you may need to do something more complicated than just appending the chunk into the array, but that's beyond the scope of this client library.

I'm going to close this issue, since the question is answered (and it seems that the library is operating correctly in any case)

When you get this working, if you think that there is a better example to help others, feel free to send a PR.
