### ISSUE TITLE
date marshaling issue on k8sApi.replaceNamespacedIngress

### ISSUE THREAD

**Issue by builat** [kubernetes-client/javascript#948]
**Describe the bug**
when call `k8sApi.replaceNamespacedIngress(....)`

issue: 
```
node_modules/@kubernetes/client-node/dist/gen/model/models.js:1915
            return data.toISOString();
                        ^
TypeError: data.toISOString is not a function
```
** Client Version **
`0.13.0` and above

** Server Version **
e.g. `1.14.0`

**To Reproduce**
call  `k8sApi.replaceNamespacedIngress(....)`

**Expected behavior**
Has no errors

** Example Code**
```typescript
import fs from "fs";
import * as dotenv from "dotenv";
import YAML from "yaml";
import * as k8s from "@kubernetes/client-node";

dotenv.config();
const kc = new k8s.KubeConfig();
kc.loadFromDefault();

const ingresConfigChanged = fs.readFileSync(
  "./config/ingres-test-config-changed.yml",
  "utf8"
);

const k8sApi = kc.makeApiClient(k8s.NetworkingV1Api);
const cfg = YAML.parse(ingresConfigChanged);
k8sApi.replaceNamespacedIngress("name", "namespace", cfg);
```
**Environment (please complete the following information):**
 - OS: MacOS 13.1 (22C65)
 - NodeJS Version 19.2.0
 - Cloud runtime Azure

**Additional context**
Relevant PR: https://github.com/kubernetes-client/javascript/pull/947

**Comment by brendandburns** [comment]
The problem here is that you are parsing raw YAML:

```javascript
const cfg = YAML.parse(ingresConfigChanged);
```

The object model for the Ingress (the creation date, I think) is a `Date` object.

Please try using the yaml helper function here:
https://github.com/kubernetes-client/javascript/blob/master/src/yaml.ts#L3

And see if that works correctly.

Alternatively, converting `ingress.metadata.creationDate` to be of type `Date` should also work.

**Comment by builat** [comment]
@brendandburns You absolutely right! Thank you!
