### ISSUE TITLE
Update types in `V1PodSpec` to allow `containers` be optional

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [kubernetes-client/javascript#984]
**Describe the bug**
Sometimes I have a function responsible for creating a Pod and this function would have a default pod spec but the function would also allow for the spec to be overriden. As such if I am calling said function and I want to update the pod spec (not in cluster, just in the function) but don't want to update the default `containers`, I don't want to pass the `containers` property at all.

But the current types makes `containers` mandatory. Even though it seems like its mandatory to enforce a container being present in the spec, that type check can easily be bypassed by passing `containers: []`. This passes the type checks without being semantically correct.

I believe this can also make it complicated if someone wants to create a pod spec for updating a pod. They will most likely not pass `containers` as they cannot be updated in cluster anyway.

** Client Version **
e.g. `0.18.1`

** Server Version **
e.g. `1.23`

**To Reproduce**
This is not a bug per se. See the Example Code section

**Expected behavior**
I want to be able to pass a pod spec without `containers` property.

** Example Code**
```ts
function mergeDefault(template: V1PodTemplateSpec) {
  const mergedPodTemplate: V1PodTemplateSpec = {
    metadata: {
      ...{
        labels: {
          task: taskId,
        },
      },
      ...template?.metadata,
    },
    spec: {
      ...{
        containers: [
          {
            name: containerName,
            image: imageName,
          },
        ],
        restartPolicy: 'Never',
      },
      ...template?.spec,
    },
  };
}
```
In the above spec, I am passing the `template` variable to optionally update the defaults. As you can see, `containers` is already given a default and I want to be able to use that default. Right now, I *have* to pass something, and if I pass `[]`, the resulting `containers` reduces to `[]`.
**Environment (please complete the following information):**
 - OS: Windows/Linux
 - NodeJS Version: 18.x.x
 - Cloud runtime: None

**Additional context**
I have given the above context in a generic way but the issue actually crops up while working with Backstage. Here is the related piece of code where I faced this issue.
https://github.com/backstage/backstage/blob/1f2b2de3fe24746297efc6596f8d5192a45c60f2/packages/backend-common/src/util/KubernetesContainerRunner.ts#L174-L200

**Comment by brendandburns** [comment]
All of this code is generated based on the OpenAPI specification and based on what is required to be sent to the server, thus the requirement that the containers field is present is defined in that specification (you can find it here: https://github.com/kubernetes/kubernetes/tree/master/api/openapi-spec)

If you want to change it to be optional, it needs to be changed in that specification, then when we regenerate the code, we will pick up that change.

However, I'm not certain a change to that spec is a good idea, since ultimately the field _is_ required when communicating with the kubernetes api server.

I'm going to close this as will not fix, since we won't change this in the client.
